import lang.stride.*;
import java.util.*;
import greenfoot.*;

public class MyWorld extends World
{
    public MyWorld()
    {
        super(600, 700, 1);
        prepare();
    }
    private void prepare()
    {
        WallHorizontal wallHorizontal =  new  WallHorizontal();
        addObject(wallHorizontal, 3, 39);
        WallHorizontal wallHorizontal2 =  new  WallHorizontal();
        addObject(wallHorizontal2, 3, 115);
        WallHorizontal wallHorizontal3 =  new  WallHorizontal();
        addObject(wallHorizontal3, 3, 194);
        WallHorizontal wallHorizontal4 =  new  WallHorizontal();
        addObject(wallHorizontal4, 3, 269);
        WallHorizontal wallHorizontal5 =  new  WallHorizontal();
        addObject(wallHorizontal5, 3, 347);
        WallHorizontal wallHorizontal6 =  new  WallHorizontal();
        addObject(wallHorizontal6, 3, 421);
        WallHorizontal wallHorizontal7 =  new  WallHorizontal();
        addObject(wallHorizontal7, 3, 500);
        WallHorizontal wallHorizontal8 =  new  WallHorizontal();
        addObject(wallHorizontal8, 3, 562);
        WallHorizontal wallHorizontal9 =  new  WallHorizontal();
        addObject(wallHorizontal9, 597, 39);
        WallHorizontal wallHorizontal10 =  new  WallHorizontal();
        addObject(wallHorizontal10, 597, 115);
        WallHorizontal wallHorizontal11 =  new  WallHorizontal();
        addObject(wallHorizontal11, 597, 192);
        WallHorizontal wallHorizontal12 =  new  WallHorizontal();
        addObject(wallHorizontal12, 597, 270);
        WallHorizontal wallHorizontal13 =  new  WallHorizontal();
        addObject(wallHorizontal13, 597, 348);
        WallHorizontal wallHorizontal14 =  new  WallHorizontal();
        addObject(wallHorizontal14, 597, 425);
        WallHorizontal wallHorizontal15 =  new  WallHorizontal();
        addObject(wallHorizontal15, 597, 501);
        WallHorizontal wallHorizontal16 =  new  WallHorizontal();
        addObject(wallHorizontal16, 597, 576);
        WallVertikal wallVertikal =  new  WallVertikal();
        addObject(wallVertikal, 39, 596);
        WallVertikal wallVertikal2 =  new  WallVertikal();
        addObject(wallVertikal2, 118, 596);
        WallVertikal wallVertikal3 =  new  WallVertikal();
        addObject(wallVertikal3, 196, 596);
        WallVertikal wallVertikal4 =  new  WallVertikal();
        addObject(wallVertikal4, 274, 596);
        WallVertikal wallVertikal5 =  new  WallVertikal();
        addObject(wallVertikal5, 353, 596);
        WallVertikal wallVertikal6 =  new  WallVertikal();
        addObject(wallVertikal6, 432, 596);
        WallVertikal wallVertikal7 =  new  WallVertikal();
        addObject(wallVertikal7, 510, 596);
        WallVertikal wallVertikal8 =  new  WallVertikal();
        addObject(wallVertikal8, 586, 596);
        WallVertikal wallVertikal9 =  new  WallVertikal();
        addObject(wallVertikal9, 114, 3);
        WallVertikal wallVertikal10 =  new  WallVertikal();
        addObject(wallVertikal10, 193, 3);
        WallVertikal wallVertikal11 =  new  WallVertikal();
        addObject(wallVertikal11, 271, 3);
        WallVertikal wallVertikal12 =  new  WallVertikal();
        addObject(wallVertikal12, 349, 3);
        WallVertikal wallVertikal13 =  new  WallVertikal();
        addObject(wallVertikal13, 428, 3);
        WallVertikal wallVertikal14 =  new  WallVertikal();
        addObject(wallVertikal14, 507, 3);
        WallVertikal wallVertikal15 =  new  WallVertikal();
        addObject(wallVertikal15, 585, 3);
        WallVertikal wallVertikal16 =  new  WallVertikal();
        addObject(wallVertikal16, 42, 61);
        WallVertikal wallVertikal17 =  new  WallVertikal();
        addObject(wallVertikal17, 42, 130);
        WallVertikal wallVertikal18 =  new  WallVertikal();
        addObject(wallVertikal18, 100, 130);
        WallHorizontal wallHorizontal17 =  new  WallHorizontal();
        addObject(wallHorizontal17, 144, 95);
        WallHorizontal wallHorizontal18 =  new  WallHorizontal();
        addObject(wallHorizontal18, 206, 43);
        WallHorizontal wallHorizontal19 =  new  WallHorizontal();
        addObject(wallHorizontal19, 206, 120);
        WallHorizontal wallHorizontal20 =  new  WallHorizontal();
        addObject(wallHorizontal20, 206, 150);
        WallVertikal wallVertikal19 =  new  WallVertikal();
        addObject(wallVertikal19, 93, 188);
        WallVertikal wallVertikal20 =  new  WallVertikal();
        addObject(wallVertikal20, 170, 188);
        WallVertikal wallVertikal21 =  new  WallVertikal();
        addObject(wallVertikal21, 41, 244);
        WallHorizontal wallHorizontal21 =  new  WallHorizontal();
        addObject(wallHorizontal21, 336, 576);
        wallHorizontal21.setLocation(335, 561);
        wallHorizontal21.setLocation(335, 574);
        WallHorizontal wallHorizontal22 =  new  WallHorizontal();
        addObject(wallHorizontal22, 470, 551);
        WallHorizontal wallHorizontal23 =  new  WallHorizontal();
        addObject(wallHorizontal23, 470, 511);
        WallVertikal wallVertikal22 =  new  WallVertikal();
        addObject(wallVertikal22, 299, 539);
        WallVertikal wallVertikal23 =  new  WallVertikal();
        addObject(wallVertikal23, 222, 539);
        WallVertikal wallVertikal24 =  new  WallVertikal();
        addObject(wallVertikal24, 148, 539);
        WallVertikal wallVertikal25 =  new  WallVertikal();
        addObject(wallVertikal25, 106, 539);
        WallHorizontal wallHorizontal24 =  new  WallHorizontal();
        addObject(wallHorizontal24, 70, 504);
        WallHorizontal wallHorizontal25 =  new  WallHorizontal();
        addObject(wallHorizontal25, 70, 435);
        WallHorizontal wallHorizontal26 =  new  WallHorizontal();
        addObject(wallHorizontal26, 70, 412);
        WallVertikal wallVertikal26 =  new  WallVertikal();
        addObject(wallVertikal26, 105, 374);
        WallHorizontal wallHorizontal27 =  new  WallHorizontal();
        addObject(wallHorizontal27, 146, 339);
        WallHorizontal wallHorizontal28 =  new  WallHorizontal();
        addObject(wallHorizontal28, 146, 278);
        WallVertikal wallVertikal27 =  new  WallVertikal();
        addObject(wallVertikal27, 106, 304);
        WallVertikal wallVertikal28 =  new  WallVertikal();
        addObject(wallVertikal28, 189, 244);
        WallVertikal wallVertikal29 =  new  WallVertikal();
        addObject(wallVertikal29, 260, 244);
        WallVertikal wallVertikal30 =  new  WallVertikal();
        addObject(wallVertikal30, 300, 244);
        WallHorizontal wallHorizontal29 =  new  WallHorizontal();
        addObject(wallHorizontal29, 270, 152);
        WallHorizontal wallHorizontal30 =  new  WallHorizontal();
        addObject(wallHorizontal30, 270, 100);
        WallVertikal wallVertikal31 =  new  WallVertikal();
        addObject(wallVertikal31, 306, 65);
        WallHorizontal wallHorizontal31 =  new  WallHorizontal();
        addObject(wallHorizontal31, 341, 100);
        WallHorizontal wallHorizontal32 =  new  WallHorizontal();
        addObject(wallHorizontal32, 341, 176);
        WallHorizontal wallHorizontal33 =  new  WallHorizontal();
        addObject(wallHorizontal33, 341, 246);
        WallHorizontal wallHorizontal34 =  new  WallHorizontal();
        addObject(wallHorizontal34, 341, 313);
        WallVertikal wallVertikal32 =  new  WallVertikal();
        addObject(wallVertikal32, 242, 298);
        WallHorizontal wallHorizontal35 =  new  WallHorizontal();
        addObject(wallHorizontal35, 208, 339);
        WallHorizontal wallHorizontal36 =  new  WallHorizontal();
        addObject(wallHorizontal36, 276, 335);
        WallVertikal wallVertikal33 =  new  WallVertikal();
        addObject(wallVertikal33, 187, 481);
        wallVertikal33.setLocation(168, 480);
        WallHorizontal wallHorizontal37 =  new  WallHorizontal();
        addObject(wallHorizontal37, 208, 409);
        WallHorizontal wallHorizontal38 =  new  WallHorizontal();
        addObject(wallHorizontal38, 208, 444);
        WallVertikal wallVertikal34 =  new  WallVertikal();
        addObject(wallVertikal34, 249, 436);
        WallVertikal wallVertikal35 =  new  WallVertikal();
        addObject(wallVertikal35, 321, 436);
        WallHorizontal wallHorizontal39 =  new  WallHorizontal();
        addObject(wallHorizontal39, 401, 470);
        WallVertikal wallVertikal36 =  new  WallVertikal();
        addObject(wallVertikal36, 366, 436);
        WallHorizontal wallHorizontal40 =  new  WallHorizontal();
        addObject(wallHorizontal40, 535, 488);
        WallVertikal wallVertikal37 =  new  WallVertikal();
        addObject(wallVertikal37, 573, 523);
        WallHorizontal wallHorizontal41 =  new  WallHorizontal();
        addObject(wallHorizontal41, 535, 413);
        wallHorizontal34.setLocation(341, 335);
        WallHorizontal wallHorizontal42 =  new  WallHorizontal();
        addObject(wallHorizontal42, 341, 292);
        WallVertikal wallVertikal38 =  new  WallVertikal();
        addObject(wallVertikal38, 378, 370);
        WallHorizontal wallHorizontal43 =  new  WallHorizontal();
        addObject(wallHorizontal43, 400, 41);
        WallHorizontal wallHorizontal44 =  new  WallHorizontal();
        addObject(wallHorizontal44, 400, 110);
        WallHorizontal wallHorizontal45 =  new  WallHorizontal();
        addObject(wallHorizontal45, 400, 181);
        WallHorizontal wallHorizontal46 =  new  WallHorizontal();
        addObject(wallHorizontal46, 400, 257);
        WallHorizontal wallHorizontal47 =  new  WallHorizontal();
        addObject(wallHorizontal47, 460, 224);
        WallHorizontal wallHorizontal48 =  new  WallHorizontal();
        addObject(wallHorizontal48, 460, 298);
        WallVertikal wallVertikal39 =  new  WallVertikal();
        addObject(wallVertikal39, 424, 370);
        wallHorizontal48.setLocation(460, 334);
        WallHorizontal wallHorizontal49 =  new  WallHorizontal();
        addObject(wallHorizontal49, 460, 334);
        wallHorizontal48.setLocation(460, 264);
        WallVertikal wallVertikal40 =  new  WallVertikal();
        addObject(wallVertikal40, 439, 125);
        WallVertikal wallVertikal41 =  new  WallVertikal();
        addObject(wallVertikal41, 586, 124);
        WallVertikal wallVertikal42 =  new  WallVertikal();
        addObject(wallVertikal42, 496, 189);
        WallVertikal wallVertikal43 =  new  WallVertikal();
        addObject(wallVertikal43, 557, 253);
        WallHorizontal wallHorizontal50 =  new  WallHorizontal();
        addObject(wallHorizontal50, 535, 352);
        WallVertikal wallVertikal44 =  new  WallVertikal();
        addObject(wallVertikal44, 558, 64);
        WallVertikal wallVertikal45 =  new  WallVertikal();
        addObject(wallVertikal45, 496, 64);
        wallHorizontal16.setLocation(593, 563);
        wallHorizontal16.setLocation(595, 558);
        wallHorizontal21.setLocation(334, 547);
        wallHorizontal21.setLocation(336, 535);
        wallHorizontal21.setLocation(336, 561);
        WallHorizontal wallHorizontal51 =  new  WallHorizontal();
        addObject(wallHorizontal51, 336, 530);
        wallVertikal23.setLocation(431, 400);
        removeObject(wallVertikal23);
        CheckPoint checkPoint =  new  CheckPoint();
        addObject(checkPoint, 174, 75);
        CheckPoint checkPoint2 =  new  CheckPoint();
        addObject(checkPoint2, 552, 32);
        CheckPoint checkPoint3 =  new  CheckPoint();
        addObject(checkPoint3, 304, 110);
        CheckPoint checkPoint4 =  new  CheckPoint();
        addObject(checkPoint4, 567, 484);
        CheckPoint checkPoint5 =  new  CheckPoint();
        addObject(checkPoint5, 297, 566);
        CheckPoint checkPoint6 =  new  CheckPoint();
        addObject(checkPoint6, 102, 339);
        AddSpeed addSpeed =  new  AddSpeed();
        addObject(addSpeed, 302, 157);
        AddSpeed addSpeed2 =  new  AddSpeed();
        addObject(addSpeed2, 497, 33);
        AddSpeed addSpeed3 =  new  AddSpeed();
        addObject(addSpeed3, 564, 436);
        AddSpeed addSpeed4 =  new  AddSpeed();
        addObject(addSpeed4, 247, 563);
        AddSpeed addSpeed5 =  new  AddSpeed();
        addObject(addSpeed5, 241, 335);
        AddSpeed addSpeed6 =  new  AddSpeed();
        addObject(addSpeed6, 106, 409);
        AddSpeed addSpeed7 =  new  AddSpeed();
        addObject(addSpeed7, 40, 95);
        Hero hero =  new  Hero();
        addObject(hero, 40, 30);
        BomHorizontal bomHorizontal =  new  BomHorizontal(1);
        addObject(bomHorizontal, 33, 215);
        BomVertikal bomVertikal =  new  BomVertikal(1);
        addObject(bomVertikal, 236, 567);
        BomHorizontal bomHorizontal2 =  new  BomHorizontal(1);
        addObject(bomHorizontal2, 559, 90);
        BomHorizontal bomHorizontal3 =  new  BomHorizontal(1);
        addObject(bomHorizontal3, 494, 401);
        BomVertikal bomVertikal2 =  new  BomVertikal(1);
        addObject(bomVertikal2, 35, 442);
        Trophy trophy =  new  Trophy();
        addObject(trophy, 552, 560);
        BtnStop btnStop = new BtnStop();
        addObject(btnStop,540,650);
        PapanScore papanScore = new PapanScore();
        addObject(papanScore,80,650);
        //CheckQuiz checkQuiz =  new  CheckQuiz();
        //addObject(checkQuiz, 502, 523);
    }
}
